- name: 安装依赖
        # 既然已经在仓库根目录了，直接安装
        run: pnpm install --no-frozen-lockfile

      - name: 精准进入子目录部署
        # 直接去找那个 packages 文件夹
        run: |
          cd packages/worker
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
